name: music
description: Scrollable, music app
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^3.0.1
  google_fonts: ^3.0.1
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.2
  firebase_storage: ^11.0.14
  firebase_database: ^10.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
  - assets/
